name: ci
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag to find in the upstream and replace here, the default is latest'
        required: false
        default: 'latest'

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      ORG: datatrails
      REPO: go-datatrails-common-api
      ARTIFACT: go-datatrails-common-api.tar.gz
    steps:
      - name: Resolve TAG
        run: |
          if [[ "$TAG" == "latest" ]]; then
            echo "::info ::resolving tag ..."
            TAG=$(curl -sL https://api.github.com/repos/${ORG}/${REPO}/releases/latest |
              jq -r ".tag_name")
          fi
          echo "::info ::resolved tag: $TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV
        env:
          TAG: ${{ inputs.tag }}

      - uses: actions/checkout@v4
        with:
          path: repo

      - name: Update the sources
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "TAG=$TAG"
          # Note that it is not forced. only non hidden files and directories
          # are removed.
          rm -r repo/*
          gh --repo $ORG/$REPO release download $TAG \
            -p 'go-datatrails-common-api-gen.tar.gz'
          # pushd repo
          # mv go-datatrails-common-api-gen.tar.gz ../
          # popd
          pushd repo
          tar -zxf ../go-datatrails-common-api-gen.tar.gz
          git status
          git log --stat
          git diff --stat
          git whatchanged
          popd