name: ci
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag to find in the upstream and replace here, the default is latest'
        required: false
        default: 'latest'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Resolve TAG
        run: |
          if [[ "$TAG" == "latest" ]]; then
            echo "::info ::resolving tag ..."
            TAG=$(curl -sL https://api.github.com/repos/${ORG}/${REPO}/releases/latest |
              jq -r ".tag_name")
          fi
          echo "::info ::resolved tag: $TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV
        env:
          TAG: ${{ inputs.tag }}
          ORG: datatrails
          REPO: go-datatrails-common-api
          ARTIFACT: go-datatrails-common-api.tar.gz

      - run: |
          echo "TAG=$TAG"


